# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q297yXxTD5k7ZCu_RucMtpd_E3rVJD5T
"""

import pandas as pd
import numpy as np
from google.colab import files

df = pd.read_excel('/content/drive/MyDrive/Pyhton_study/Applicants.xlsx')



# Split the Interviewrs names & Fit to account columns
df[['Interviewer_1','Interviewer_2','Interviewer_3']] = df["Interviewers names"].str.split(';',n=2, expand=True)


df[['fit_to_account_1','fit_to_account_2','fit_to_account_3']] = df["fit_to_account"].str.split(',',n=2, expand=True)

# Drop the interviewers names  & Fit to account column after splitting it
df = df.drop(columns="Interviewers names")
df = df.drop(columns="fit_to_account")

# Adjust fit to account column

df = df.replace('[]','')

# Adjust time format to be the same

df['Technical interview date'] = pd.to_datetime(df['Technical interview date'])
df['Technical interview date'] = df['Technical interview date'].dt.strftime('%m-%d-%Y %H:%M')

df['Board interview date'] = pd.to_datetime(df['Board interview date'])
df['Board interview date'] = df['Board interview date'].dt.strftime('%m-%d-%Y %H:%M')

df['Created'] = pd.to_datetime(df['Created'])
df['Created'] = df['Created'].dt.strftime('%m-%d-%Y %H:%M')

df['Modified'] = pd.to_datetime(df['Modified'])
df['Modified'] = df['Modified'].dt.strftime('%m-%d-%Y %H:%M')

#fill null values
df['Role ID'] = df['Role ID'].fillna('0')
df['Level ID'] = df['Level ID'].fillna('0')
df['Level ID'] = df['Level ID'].fillna('0')


#Dates
df['Technical interview date'] = df['Technical interview date'].fillna('1/1/2222 00:00')
df['Board interview date']     = df['Board interview date']    .fillna('1/1/2222 00:00')

# Switch commas to score to avoid erros in ETL
df['Created By'] = df['Created By'].str.replace(',', '-')
df['Modified By'] = df['Modified By'].str.replace(',', '-')

df['Interviewer_1'] = df['Interviewer_1'].str.replace(',', '-')
df['Interviewer_2'] = df['Interviewer_2'].str.replace(',', '-')
df['Interviewer_3'] = df['Interviewer_3'].str.replace(',', '-')

#edit data types
df['ID'] = df['ID'].astype(int)


df['Status ID'] = df['Status ID'].astype(int)
df['Role ID']   = df['Role ID'].astype(int)
df['Level ID']  = df['Level ID'].astype(int)



df['Technical interview date'] = pd.to_datetime(df['Technical interview date'], format='mixed', dayfirst=True)

df['Board interview date'] =   pd.to_datetime(df['Board interview date'],       format='mixed', dayfirst=True)

df['Created'] = pd.to_datetime(df['Created'], format='mixed', dayfirst=True)

df['Modified'] = pd.to_datetime(df['Modified'], format='mixed', dayfirst=True)

df.to_csv('preprocessed_data.csv', index=False)
files.download('preprocessed_data.csv')